### ISSUE TITLE
URL wrong for 2011-12-01

### ISSUE THREAD

**Issue by REOScotte** [rharish101/dilbert-viewer#10]
The URL for 2011-12-01 is wrong. I listed the correct URL in this script that I used to download all pics. Also some of the titles have leading spaces - not sure if thats coming from the wayback machine or not.

https://github.com/REOScotte/MiscPowerShell/blob/master/DownloadDilbert.ps1

**Comment by rharish101** [comment]
Thanks for the report. I found out that the issue is in the archives at archive.org. The viewer uses the earliest possible archive to find the URLs, but the earliest possible archive for 2011-12-01 is wrong (but later archives for the same date are fine). I'll try to fiddle with the way I'm scraping from archive.org and close this issue when I found a satisfactory solution.

**EDIT**: I fixed the URL in the cache, so it should be temporarily fixed.

**Comment by rharish101** [comment]
By the way, is every other URL correct? I'm assuming that you used your script to download every comic.

**Comment by REOScotte** [comment]
Yes, I downloaded all the others successfully and they all have unique hashes so I know they're all different. But I haven't yet looked at all of them to confirm 😁

Another thing I noticed is that some are lower resolution than most. I wonder if a newer version has higher resolution.

________________________________

**Comment by rharish101** [comment]
I've "fixed" this by choosing the archive that is closest in date to 2018. Hopefully this leads to proper archive.org copies.
